nspecies: 2
infile: all_loci.fasta
region: coding
nameA: chi
nameB: ros
nameOutgroup: num
max_N_tolerated: 0.1
Lmin: 30
nMin: 12
mu: 0.000000003
rho_over_theta: 1
N_min: 0
N_max: 200000
Tsplit_min: 0
Tsplit_max: 200000
M_min: 0
M_max: 10
