nspecies: 1
mail_address: test@gmail.com
config_yaml: /home/croux/Documents/ABConline/1pop/config.yaml
infile: /home/croux/Documents/ABConline/all_loci.fasta
timeStamp: Ng4PymB1dy
region: coding
nameA: chi
nameOutgroup: num
max_N_tolerated: 0.1
Lmin: 100
nMin: 12
mu: 0.000000003
rho_over_theta: 1
N_min: 0
N_max: 1000000
Tchanges_min: 0
Tchanges_max: 1500000
