nmultilocus = 1000 # number of multilocus simulations per iteration (500)
nIterations_model_comp = 5 # number of subdirectories for the simulations used in the RF model comparison
nIterations_estim = 1 # number of subdirectories for the simulations used in the nnet param estimates (2000)
nIterations_gof = 1 # number of subdirectories for the simulations used in the nnet param estimates (200)
nCPU_R = 8 # number of CPUs for the model comp for the model forest R functions
ntree = 2000 # number of tree for the random forest (RF) model comparison


MODELS_COMP = ['Constant_1N', 'Constant_2N', 'Discrete_1N', 'Discrete_2N', 'Expo_1N', 'Expo_2N']
ITERATIONS_MODEL_COMP = range(nIterations_model_comp)
ITERATIONS_ESTIMATES = range(nIterations_estim)
ITERATIONS_GOF = range(nIterations_gof)


mail_address = config['mail_address']
infile = config['infile']
region = config['region']
nspecies = config['nspecies']
nameA = config['nameA']
nameOutgroup = config['nameOutgroup']
if nameOutgroup=='NA':
	outgroup=0
else:
	outgroup=1
config_yaml = config['config_yaml']
timeStamp = config['timeStamp']
submit_simulations='submit_simulations_1pop.py'
submit_simulations_gof='submit_simulations_gof_1pop.py'
max_N_tolerated = config['max_N_tolerated']
Lmin = config['Lmin']
nMin = config['nMin']
mu = config['mu']
rho_over_theta = config['rho_over_theta']


rule targets:
	input:
		expand("{timeStamp}/general_infos.txt", timeStamp=timeStamp),
		expand("{timeStamp}/{nameA}_infos.txt", timeStamp=timeStamp, nameA=nameA),
		expand("{timeStamp}/ABCstat_global.txt", timeStamp=timeStamp),
		expand("{timeStamp}/ABCstat_loci.txt", timeStamp=timeStamp),
		expand("{timeStamp}/ABCjsfs.txt", timeStamp=timeStamp),
		expand("{timeStamp}/sfs_plot.pdf", timeStamp=timeStamp),
		expand("{timeStamp}/sfs_table.txt", timeStamp=timeStamp),
		expand("{timeStamp}/results_recombination.txt", timeStamp=timeStamp),
		expand("{timeStamp}/modelComp/report_{nameA}.txt", timeStamp=timeStamp, nameA=nameA),
		expand("{timeStamp}/modelComp/best_model.txt", timeStamp=timeStamp),
		expand("{timeStamp}/modelComp/hierarchical_models.txt", timeStamp=timeStamp),
		expand("{timeStamp}/modelComp/locus_specific_modelComp.txt", timeStamp=timeStamp),
		expand("{timeStamp}/best_model/report_{nameA}.txt", timeStamp=timeStamp, nameA=nameA),
		expand("{timeStamp}/best_model/posterior_bestModel.txt", timeStamp=timeStamp),
		expand("{timeStamp}/best_model/posterior_bestModel.pdf", timeStamp=timeStamp),
		expand("{timeStamp}/gof/goodness_of_fit_test.txt", timeStamp=timeStamp),
		expand("{timeStamp}/gof/gof_sfs.txt", timeStamp=timeStamp)
	shell:
		"""
		tar -zcvf {timeStamp}.tar.gz {input}
		rm slurm*out
#		rm -rf {timeStamp}		
		"""

rule fasta2ABC_1pop:
	params:
		nameA={nameA},
		nameOutgroup={nameOutgroup},
		region={region},
		Lmin={Lmin},
		max_N_tolerated={max_N_tolerated},
		nMin={nMin},
		mu={mu},
		rho_over_theta={rho_over_theta}
	input:
		expand("{infile}", infile=infile)
	output:
		expand("{timeStamp}/general_infos.txt", timeStamp=timeStamp),
		expand("{timeStamp}/ABCjsfs.txt", timeStamp=timeStamp),
		expand("{timeStamp}/ABCstat_global.txt", timeStamp=timeStamp),
		expand("{timeStamp}/ABCstat_loci.txt", timeStamp=timeStamp),
		expand("{timeStamp}/bpfile", timeStamp=timeStamp),
		expand("{timeStamp}/nLoci.txt", timeStamp=timeStamp),
		expand("{timeStamp}/{nameA}_infos.txt", timeStamp=timeStamp, nameA=nameA),
		expand("{timeStamp}/{nameA}.ms", timeStamp=timeStamp, nameA=nameA)
	threads: 8
	shell:
		"""
		x=$(date)
		fasta2ABC_1pop.py {infile} {timeStamp} {params.nameA} {params.nameOutgroup} {params.region} {params.Lmin} {params.max_N_tolerated} {params.nMin} {params.mu} {params.rho_over_theta}
		echo "nSpecies,"{nspecies}>{timeStamp}/general_infos.txt
		echo "nameA,"{nameA}>>{timeStamp}/general_infos.txt
		y=$( cat {timeStamp}/nLoci.txt )
		echo "nLoci,"${{y}}>>{timeStamp}/general_infos.txt
		echo "mail,"{mail_address}>>{timeStamp}/general_infos.txt
		echo "date,"${{x}}>>{timeStamp}/general_infos.txt
		"""

rule RNAseqFGT:
	params:
		nameA={nameA}
	input:
		infos=expand("{timeStamp}/{nameA}_infos.txt", timeStamp=timeStamp, nameA=nameA),
		fasta=expand("{infile}", infile=infile),
		nLoci=expand("{timeStamp}/nLoci.txt", timeStamp=timeStamp),
	output:
		expand("{timeStamp}/results_recombination.txt", timeStamp=timeStamp)
	threads: 1
	shell:	
		"""
		x=$(cat {input.infos}  | grep -v locusName | awk '{{print $2}}' | sort -n | tail -n1)
		if (($x<99990)); then
			RNAseqFGT {input.fasta} {output}
		else
			echo "{input.fasta} not in correct FASTA format (line length > 100000)" > {output}
		fi
		"""

rule simulationsModelComp:
	params:
		nmultilocus={nmultilocus}
	input:
		"{timeStamp}/bpfile",
		"{timeStamp}/nLoci.txt"
	output:
		"{timeStamp}/modelComp/{model}_{i}/bpfile",
		"{timeStamp}/modelComp/{model}_{i}/priorfile.txt",
		"{timeStamp}/modelComp/{model}_{i}/ABCstat.txt"
	threads: 1
	shell:
		"""
		{submit_simulations} {outgroup} {params.nmultilocus} {wildcards.i} {wildcards.model} {nameA} modelComp {wildcards.model} {config_yaml} {timeStamp}
		"""

rule modelComparison:
	params:
		nameOutgroup={nameOutgroup}
	input:
		expand("{timeStamp}/ABCstat_global.txt", timeStamp=timeStamp),
		expand("{timeStamp}/ABCstat_loci.txt", timeStamp=timeStamp),
		expand("{timeStamp}/modelComp/{model}_{i}/ABCstat.txt", timeStamp=timeStamp, model=MODELS_COMP, i=ITERATIONS_MODEL_COMP)
	output:
		expand("{timeStamp}/modelComp/report_{nameA}.txt", timeStamp=timeStamp, nameA=nameA),
		expand("{timeStamp}/modelComp/locus_specific_modelComp.txt", timeStamp=timeStamp),
		expand("{timeStamp}/modelComp/best_model.txt", timeStamp=timeStamp),
		expand("{timeStamp}/modelComp/hierarchical_models.txt", timeStamp=timeStamp),
		expand("{timeStamp}/sfs_plot.pdf", timeStamp=timeStamp),
		expand("{timeStamp}/sfs_table.txt", timeStamp=timeStamp)
	threads: nCPU_R
	shell:
		"""
		model_comp_1pop_allModels.R nameA={nameA} timeStamp={timeStamp} nMin={nMin} sub_dir_sim=modelComp nSubdir={nIterations_model_comp} ntree={ntree} ncores={nCPU_R} outgroup={outgroup}
		"""

rule simulation_best_model:
	params:
		nmultilocus={nmultilocus}
	input:
		best="{timeStamp}/modelComp/best_model.txt",
		bpfile="{timeStamp}/bpfile",
		nLoci="{timeStamp}/nLoci.txt",
	output:
		"{timeStamp}/best_model/best_model_{i}/priorfile.txt",
		"{timeStamp}/best_model/best_model_{i}/ABCstat.txt"
	threads: 1
	shell:
		"""
		best_model=$(cat {input.best})
		{submit_simulations} {outgroup} {params.nmultilocus} {wildcards.i} ${{best_model}} {nameA} best_model best_model {config_yaml} {timeStamp}
		"""

rule estimation_best_model:
	input:
		best=expand("{timeStamp}/modelComp/best_model.txt", timeStamp=timeStamp),
		obs=expand("{timeStamp}/ABCstat_global.txt", timeStamp=timeStamp),
		simulations=expand("{timeStamp}/best_model/best_model_{i}/ABCstat.txt", timeStamp=timeStamp, i=ITERATIONS_ESTIMATES)
	output:
		expand("{timeStamp}/best_model/report_{nameA}.txt", timeStamp=timeStamp, nameA=nameA),
		expand("{timeStamp}/best_model/posterior_bestModel.txt", timeStamp=timeStamp),
		expand("{timeStamp}/best_model/posterior_bestModel.pdf", timeStamp=timeStamp)
	threads: nCPU_R
	shell:
		"""
		best_model=$(cat {input.best})
		estimates_1pop_best.R nameA={nameA} nMin={nMin} sub_dir_sim=best_model nSubdir={nIterations_estim} ntree={ntree} ncores={nCPU_R} outgroup={outgroup} bestModel=${{best_model}} timeStamp={timeStamp}
		"""
rule simulation_gof:
	params:
		nmultilocus={nmultilocus}
	input:
		best="{timeStamp}/modelComp/best_model.txt",
		posterior="{timeStamp}/best_model/posterior_bestModel.txt"
	output:
		"{timeStamp}/gof/gof_{i}/ABCstat.txt"
	shell:
		"""
		best_model=$(cat {input.best})
		{submit_simulations_gof} {outgroup} {params.nmultilocus} {wildcards.i} ${{best_model}} {nameA} gof gof ${{PWD}}/{input.posterior} {timeStamp}
		"""

rule gof:
	input:
		expand("{timeStamp}/ABCstat_global.txt", timeStamp=timeStamp),
		expand("{timeStamp}/ABCjsfs.txt", timeStamp=timeStamp),
		expand("{timeStamp}/gof/gof_{i}/ABCstat.txt", timeStamp=timeStamp, i=ITERATIONS_GOF)
	output:
		"{timeStamp}/gof/goodness_of_fit_test.txt",
		"{timeStamp}/gof/gof_sfs.txt"
	shell:
		"""
		head -n1 {timeStamp}/gof/gof_0/ABCstat.txt > {timeStamp}/gof/simulations.txt
		cat {timeStamp}/gof/gof*/ABCstat.txt | grep -v avg >> {timeStamp}/gof/simulations.txt
		
		head -n1 {timeStamp}/gof/gof_0/ABCjsfs.txt > {timeStamp}/gof/simulations_jsfs.txt
		cat {timeStamp}/gof/gof*/ABCjsfs.txt | grep -v fA >> {timeStamp}/gof/simulations_jsfs.txt
		
		gof_1pop.R timeStamp={timeStamp}
		"""
